return {
  runtime = {
    log_level = "DEBUG",
    environment = "test",
    agent_timeout_seconds = 120,
  },

  channels = {
    telegram = {
      enabled = true,
      bot_token = "",
      allowed_chat_ids = {},
      allowed_user_ids = {},
      require_authorized = true,
      mode = "long_polling",
      webhook_url = "",
      media_enabled = true,
      max_photo_bytes = "5MB",
      max_document_bytes = "10MB",
      max_total_media_bytes = "12MB",
      max_attachments_per_message = 3,
      allowed_document_mime_types = {},
    },
  },

  llm = {
    provider = "openai_responses",
    base_url = "",
    model = "gpt-5-mini",
    max_tool_iterations = 15,
    request_timeout_seconds = 45,
    sock_connect_timeout_seconds = 10,
    sock_read_timeout_seconds = 45,
    retry_attempts = 3,
    retry_delay_seconds = 2.0,
    system_prompt = "You are Minibot, a helpful assistant.",
    prompts_dir = "./prompts",
    openrouter = {
      models = {},
      plugins = {},
      provider = {
        provider_extra = {},
      },
    },
  },

  providers = {
    openai = {
      api_key = os.getenv("OPENAI_API_KEY") or "",
      base_url = "",
    },
    openai_responses = {
      api_key = os.getenv("OPENAI_API_KEY") or "",
      base_url = "",
    },
    openrouter = {
      api_key = os.getenv("OPENROUTER_API_KEY") or "",
      base_url = "",
    },
    claude = {
      api_key = os.getenv("CLAUDE_API_KEY") or "",
      base_url = "",
    },
    google = {
      api_key = os.getenv("GEMINI_API_KEY") or "",
      base_url = "",
    },
  },

  orchestration = {
    directory = "./agents",
    default_timeout_seconds = 90,
    tool_ownership_mode = "exclusive",
    main_agent = {
      name = "minibot",
      tools_allow = { "current_*", "calculate_*", "http_*", "*_agent*" },
    },
  },

  memory = {
    backend = "sqlite",
    sqlite_url = "sqlite+aiosqlite:///./testdata/minibot.db",
    max_history_messages = 200,
  },

  scheduler = {
    prompts = {
      enabled = true,
      sqlite_url = "sqlite+aiosqlite:///./testdata/scheduled_prompts.db",
      poll_interval_seconds = 60,
      lease_timeout_seconds = 120,
      batch_size = 10,
      max_attempts = 3,
      min_recurrence_interval_seconds = 60,
      pool_size = 5,
      echo = false,
    },
  },

  tools = {
    kv_memory = {
      enabled = true,
      sqlite_url = "sqlite+aiosqlite:///./testdata/kv_memory.db",
      pool_size = 5,
      echo = false,
      default_limit = 20,
      max_limit = 100,
      default_owner_id = "primary",
    },
    http_client = {
      enabled = true,
      timeout_seconds = 10,
      max_bytes = "16KB",
      response_processing_mode = "auto",
      max_chars = 6000,
      normalize_whitespace = true,
    },
    file_storage = {
      enabled = true,
      root_dir = "./testdata/files",
      max_write_bytes = "64KB",
      allow_outside_root = false,
      save_incoming_uploads = false,
      uploads_subdir = "uploads",
      incoming_temp_subdir = "uploads/temp",
    },
    grep = {
      enabled = false,
      max_matches = 200,
      max_file_size_bytes = "1MB",
    },
    audio_transcription = {
      enabled = false,
      model = "small",
      device = "auto",
      compute_type = "int8",
      beam_size = 5,
      vad_filter = true,
      auto_transcribe_short_incoming = true,
      auto_transcribe_max_duration_seconds = 45,
    },
    lua_custom = {
      enabled = false,
      directory = "./testdata/lua_tools",
    },
    calculator = {
      enabled = true,
      default_scale = 28,
      max_expression_length = 200,
      max_exponent_abs = 1000,
    },
    python_exec = {
      enabled = true,
      backend = "host",
      python_path = "",
      venv_path = "",
      sandbox_mode = "basic",
      default_timeout_seconds = 8,
      max_timeout_seconds = 20,
      max_output_bytes = "64KB",
      max_code_bytes = "32KB",
      artifacts_enabled = true,
      artifacts_default_subdir = "generated",
      artifacts_allowed_extensions = {
        ".png",
        ".jpg",
        ".jpeg",
        ".pdf",
        ".csv",
        ".txt",
        ".json",
        ".svg",
      },
      artifacts_max_files = 5,
      artifacts_max_file_bytes = "5MB",
      artifacts_max_total_bytes = "20MB",
      artifacts_allow_in_jail = false,
      artifacts_jail_shared_dir = "",
      pass_parent_env = false,
      env_allowlist = { "PATH", "LANG", "LC_ALL", "PYTHONUTF8" },
      rlimit = {
        enabled = false,
        cpu_seconds = 2,
        memory_mb = 256,
        fsize_mb = 16,
        nproc = 64,
        nofile = 256,
      },
      cgroup = {
        enabled = false,
        driver = "systemd",
        cpu_quota_percent = 100,
        memory_max_mb = 256,
      },
      jail = {
        enabled = false,
        command_prefix = {},
      },
    },
    time = {
      enabled = true,
      default_format = "%Y-%m-%dT%H:%M:%SZ",
    },
    bash = {
      enabled = false,
      default_timeout_seconds = 15,
      max_timeout_seconds = 120,
      max_output_bytes = "128KB",
      pass_parent_env = true,
      env_allowlist = { "PATH", "HOME", "USER", "LANG", "LC_ALL", "SHELL" },
    },
    apply_patch = {
      enabled = false,
      restrict_to_workspace = true,
      workspace_root = ".",
      allow_outside_workspace = false,
      preserve_trailing_newline = true,
      max_patch_bytes = "256KB",
    },
    mcp = {
      enabled = true,
      name_prefix = "mcp",
      timeout_seconds = 10,
      servers = {
        {
          name = "playwright-cli",
          transport = "stdio",
          command = "npx",
          args = {
            "@playwright/mcp@0.0.64",
            "--headless",
            "--browser=chromium",
            "--caps=vision,pdf,network",
            "--block-service-workers",
            "--image-responses=omit",
            "--snapshot-mode=incremental",
            "--timeout-action=2000",
            "--timeout-navigation=8000",
            "--output-dir=./testdata/files/browser",
          },
          env = {},
          cwd = ".",
        },
      },
    },
  },

  logging = {
    structured = true,
    logfmt_enabled = true,
    log_level = "DEBUG",
    kv_separator = "=",
    record_separator = " ",
  },
}
